### ISSUE TITLE
Compilation error: cannot implicitly convert expression

### ISSUE THREAD

**Issue by mbierlee** [nykytenko/onyx-config#3]
The following error is shown when compiling my program when including onyx-log as dependency:
```
onyx-config-2.0.3\source\onyx\bundle.d(889,21): Error: cannot implicitly convert expression (separatorPos) of type long to uint
onyx-config-2.0.3\source\onyx\bundle.d(890,23): Error: cannot implicitly convert expression (separatorPos + cast(long)separator.length) of type long to uint
dmd failed with exit code 1.
```

Compiled on Windows 10 using DMD 2.069.2 and DUB 0.9.24

**Comment by nykytenko** [comment]
Can I see you configuration file for creating logger by onyx-log?

**Comment by nykytenko** [comment]
Hi, mbierlee.
I make changes for fix this issue in v2.0.4, but I have't got a Windows for testing. Try to use this new version.

**Comment by mbierlee** [comment]
Compilation errors are resolved now

**Comment by nykytenko** [comment]
Thank, mbierlee.
