### ISSUE TITLE
ascsii support

### ISSUE THREAD

**Issue by bubnenkoff** [nykytenko/onyx-config#4]
When I am trying to open config in ascii I am getting error:
`core.exception.UnicodeException@src\rt\util\utf.d(290): invalid UTF-8 sequence`

**Comment by nykytenko** [comment]
Could you send me such minimal file for testing.

**Comment by bubnenkoff** [comment]
Honestly I do not remember file that I used for test, but it's seems that it's common bug with https://github.com/jasonwhite/io/issues/7
There is example of file.

**Comment by nykytenko** [comment]
Your example file "123.rsm" saved with Windows-1251 encoding and contains non ASCII symbols!  You must save files with UTF-8 encoding for using with onyx-config library. onyx-config library support files saved only with UTF-8 encoding.
